version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "./setup/package.yaml" }}-{{ checksum "./setup/stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: cd setup && stack setup
      - run:
          name: Install executable
          command: cd setup && stack install
      - save_cache:
          name: Cache Dependencies
          key: archsetup-v1-{{ checksum "./setup/package.yaml" }}-{{ checksum "./setup/stack.yaml" }}
          paths:
            - "./setup/.stack"
            - "./setup/.stack-work"
      - store_artifacts:
          path: ~/.local/bin/archsetup-exe
          destination: archsetup-exe
