stow --target="$HOME" i3
stow --target="$HOME" i3blocks
stow --target="$HOME" urxvt
stow --target="$HOME" xresources
stow --target="$HOME" emacs
stow --target="$HOME" git
stow --target="$HOME" qutebrowser
sudo stow --target=/etc networkmanager
sudo stow --target=/etc vconsole
stow --target="$HOME" ranger
stow --target="$HOME" mutt
stow --target="$HOME" compton
stow --target="$HOME" taskwarrior
stow --target="$HOME" lein
stow --target="$HOME" maninex
stow --target="$HOME" redshift
stow --target="$HOME" taskwarrior
stow --target="$HOME" dunst
stow --target="$HOME" dircolors
stow --target="$HOME" bin
stow --target="$HOME" ghci
stow --target="$HOME" inputrc
stow --target="$HOME" bash
stow --target="$HOME" xinit
stow --target="$HOME" gtk
stow --target="$HOME" xmodmap
sudo stow --target=/etc bluetooth
sudo stow --target=/etc pulseaudio
