stow --target="$HOME" i3
stow --target="$HOME" i3blocks
stow --target="$HOME" urxvt
stow --target="$HOME" xresources
stow --target="$HOME" emacs
stow --target="$HOME" git
stow --target="$HOME" qutebrowser
sudo stow --target=/etc networkmanager
sudo stow --target=/etc vconsole
stow --target="$HOME" ranger
stow --target="$HOME" mutt
stow --target="$HOME" compton
stow --target="$HOME" taskwarrior
stow --target="$HOME" lein
stow --target="$HOME" powerline
stow --target="$HOME" maninex
