export PATH=$PATH:"$HOME/Android/Sdk/tools/"
export PATH=$PATH:"$HOME/Android/Sdk/platform-tools/"
export PATH=$PATH:"/opt/pypy3/bin/"
export PATH=$PATH:"$HOME/.bin/"
export PATH=$PATH:"$HOME/.local/bin/"
export PATH=$PATH:"$HOME/.gem/ruby/2.4.0/bin"
export PATH=$PATH:"$HOME/.yarn/bin"
export PATH=$PATH:"$HOME/.cabal/bin"
export PATH=$PATH:"$HOME/flutter/bin/cache/dart-sdk/bin"
export PATH=$PATH:"$HOME/flutter/bin"
export PATH=$PATH:"$HOME/.pub-cache/bin"

export GOPATH="$HOME/go"
export PATH="${PATH}:$GOPATH/bin"
