#!/bin/sh
# WIN=$(xdotool getactivewindow)
#
# if [ -n "$WIN" ];
#    then
#        xtitle -f "%s " #| strcut
#    else
#        exit 0
#    fi

xdotool getactivewindow getwindowname

case $BLOCK_BUTTON in
    1) i3-msg layout tabbed ;; #left click tabbed layout
    2) i3-msg layout stacked ;; #middle click stacked
    3) i3-msg layout toggle split ;; #right click
esac
