name:                archsetup
version:             0.1.0.0
github:              "panavtec/dotfiles"
license:             BSD3
author:              "Christian Panadero"
maintainer:          "panavtec@gmail.com"
copyright:           "UNLICENSED"

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/panavtec/dotfiles#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- text
- wreq
- lens
- bytestring

library:
  source-dirs: src

executables:
  archsetup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - archsetup
