name:                archsetup
version:             0.1.0.0
github:              "panavtec/dotfiles"
license:             BSD3
author:              "Christian Panadero"
maintainer:          "panavtec@gmail.com"
copyright:           "UNLICENSED"

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/panavtec/dotfiles#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- text
- transformers
- turtle
- wreq
- http-client

library:
  source-dirs: src

executables:
  archsetup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wsemigroup
    - -Wmissing-monadfail-instances
    - -Wnoncanonical-monoid-instances
    - -Wnoncanonical-monad-instances
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wmissing-home-modules
    - -Werror
    dependencies:
    - archsetup
